# -*- coding: utf-8 -*-
"""Cat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vvBj5UpfpzYblEuqxT9-nbPQwE225Mca
"""

import matplotlib.pyplot as plt
from skimage.io import imread

url = 'https://raw.githubusercontent.com/williamedwardhahn/Data_Sci/main/dataset/train/cat/download.jpg'



im = imread(url)
plt.figure(figsize=(20,10))
plt.imshow(im)
plt.axis('off');

im.shape

plt.imshow(im)

im[:,:,2].shape

plt.imshow(im[:,:,0],cmap='gray')

plt.imshow(im[:,:,1],cmap='gray')

plt.imshow(im[:,:,2],cmap='gray')

plt.imshow(im[:,:,:],cmap='gray')

plt.imshow(im[120:150,:,1],cmap='gray')

plt.imshow(im[:,:,1],cmap='gray')

plt.imshow(im[:,140:180,1],cmap='gray')

plt.imshow(im[100:130,140:180,:],cmap='jet')

plt.imshow(im[100:130,140:180,0],cmap='jet')

import numpy as np

W = np.zeros((100,100,3))
plt.imshow(W)

W = np.ones((100,100,3))
plt.imshow(W)

W = np.zeros((100,100,3))

W[:,:,0] = 1

plt.imshow(W)

W = np.zeros((100,100,3))

W[:,:,1] = 1

plt.imshow(W)

W = np.zeros((100,100,3))

W[:,:,2] = 1

plt.imshow(W)

W = np.zeros((100,100,3))

W[0:10,:,0] = 1

W[40:50,:,1] = 1

W[70:80,20:25,2] = 1 

plt.imshow(W)

